#!/usr/bin/env bash
# Use of loops to solve the fizzbuzz project
a=1
while [ "$a" -lt 101 ];
do
    if [ $((a % 15)) = 0 ];
    then
        echo "FizzBuzz"
    elif [ $((a % 3)) = 0 ];
    then
        echo "Fizz"
    elif [ $((a % 5)) = 0 ];
    then
        echo "Buzz"
    else
        echo "$a"
    fi
    ((a++))
done
