#!/usr/bin/env bash
# This script is displaying "Best School" 10 times followed by Hi
a=0
while [ "$a" -lt 9 ];
do
    echo "Best School"
    ((a++))
    if [ "$a" -eq 9 ];
    then
        echo "Hi"
    fi
done
