#!/usr/bin/env bash
#Resolves the current local host to a different local host
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
